CREATE TABLE Awards(
	awardID INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(32)
);

CREATE TABLE Entertainment(
	eid INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(64) NOT NULL,
	release_date VARCHAR(128),
	genre VARCHAR(64) NOT NULL,
	num_in_stock INTEGER NOT NULL,
	sequal_id INTEGER,
    platform VARCHAR(64),
	version VARCHAR(64)
);

CREATE TABLE Address(
	aid INTEGER PRIMARY KEY AUTO_INCREMENT,
	state VARCHAR(2) NOT NULL,
	city VARCHAR(32) NOT NULL,
	street VARCHAR(64) NOT NULL,
	zip INTEGER NOT NULL
);

CREATE TABLE Sub_Plan(
	level_id INTEGER PRIMARY KEY,
	total_quota INTEGER NOT NULL
);

CREATE TABLE Users(
	user_email VARCHAR(128) PRIMARY KEY,
	name VARCHAR(32) NOT NULL,
	pass VARCHAR(32) NOT NULL,
	phone VARCHAR(10),
	aid INTEGER	NOT NULL,
	is_admin BOOLEAN NOT NULL,
	level_id INTEGER NOT NULL,
    FOREIGN KEY (aid) REFERENCES Address(aid),
    FOREIGN KEY (level_id) REFERENCES Sub_Plan(level_id)
);

CREATE TABLE Rent_History(
	rid INTEGER PRIMARY KEY AUTO_INCREMENT,
	eid INTEGER NOT NULL,
	user_email VARCHAR(128) NOT NULL,
	time_rented DATETIME DEFAULT NULL,
	time_returned TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (eid) REFERENCES Entertainment(eid) ON DELETE NO ACTION,
    FOREIGN KEY (user_email) REFERENCES Users(user_email) ON DELETE NO ACTION
);

CREATE TABLE Cast_Member(
	cid INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(32) NOT NULL,
    aid INTEGER NOT NULL,
    is_director BOOLEAN NOT NULL,
    FOREIGN KEY (aid) REFERENCES Address(aid)
);

CREATE TABLE Worked_In(
	cid INTEGER,
	eid INTEGER,
	PRIMARY KEY(cid,eid),
    FOREIGN KEY (cid) REFERENCES Cast_Member(cid) ON DELETE CASCADE,
    FOREIGN KEY (eid) REFERENCES Entertainment(eid) ON DELETE CASCADE
);

CREATE TABLE Won(
	eid INTEGER,
    awardID INTEGER,
    PRIMARY KEY(eid,awardID),
    FOREIGN KEY (eid) REFERENCES Entertainment(eid) ON DELETE CASCADE,
    FOREIGN KEY (awardID) REFERENCES Awards(awardID) ON DELETE CASCADE
);